import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <header>
        <div className=" w-full py-3 bg-slate-500 flex justify-between px-5 ">

          <div className="">
            <Link
              className="bg-black px-3 w-28 text-center py-2 my-2 mx-1 rounded-full border-2  hover:bg-slate-400 hover:text-black  hover:border-[black] font-medium  leading-tight text-white shadow-md transition duration-150 ease-in-out hover:shadow-lg focus:shadow-lg focus:outline-none active:shadow-lg"
              href="/"
            >
              Home
            </Link>
            <Link
              className="bg-black px-3 w-28 text-center py-2 my-2 mx-1 rounded-full border-2  hover:bg-slate-400 hover:text-black  hover:border-[black] font-medium  leading-tight text-white shadow-md transition duration-150 ease-in-out hover:shadow-lg focus:shadow-lg focus:outline-none active:shadow-lg"
              href="/name/"
            >
              Name
            </Link>
            <Link
              className="bg-black px-3 w-28 text-center py-2 my-2 mx-1 rounded-full border-2  hover:bg-slate-400 hover:text-black  hover:border-[black] font-medium  leading-tight text-white shadow-md transition duration-150 ease-in-out hover:shadow-lg focus:shadow-lg focus:outline-none active:shadow-lg"
              href="/name/address/"
            >
              Address
            </Link>
            </div>
            <div>
            <Link
              className="bg-black px-3  text-center py-2 my-2 rounded-full border-2  hover:bg-slate-400 hover:text-black  hover:border-[black] font-medium  leading-tight text-white shadow-md transition duration-150 ease-in-out hover:shadow-lg focus:shadow-lg focus:outline-none active:shadow-lg"
              href="/login/"
            >
              Login/SignUp
            </Link>
          </div>
          </div>
        </header>
        {/* <div className="wrapper flex flex-col bg-gray-900 h-screen px-3 items-center justify-around rounded-3xl"></div> */}
        {children}
        
      </body>
    </html>
  );
}
