import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarShortcut,
  MenubarTrigger,
} from "@/components/ui/menubar"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>My Projects</title>
      </head>
      <body className={inter.className}>
        <div>
          <div className="flex bg-slate-900 my-0.5 justify-start ">
            <Link
              href="/"
              className="px-5 py-2.5 hover:text-green-500 text-white"
            >
              {" "}
              Home{" "}
            </Link>
            <Link
              href="/counter"
              className="px-5 py-2.5 hover:text-green-500 text-white"
            >
              {" "}
              Counter{" "}
            </Link>
            <Link
              href="/bgchanger"
              className="px-5 py-2.5 hover:text-green-500 text-white"
            >
              {" "}
              Background Changer{" "}
            </Link>
            <Link
              href="/timer"
              className="px-5 py-2.5 hover:text-green-500 text-white"
            >
              {" "}
              Timer{" "}
            </Link>
            <Link
              href="/passgenerator"
              className="px-5 py-2.5 hover:text-green-500 text-white"
            >
              {" "}
              Password Generator{" "}
            </Link>
          </div>
          
        </div>
        {children}
      </body>
    </html>
  );
}
