import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


import TopNavigation from "@/components/ui/topNavigationMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>My Projects</title>
      </head>
      <body className={inter.className} style={{ backgroundColor: "black" }}>
        <TopNavigation />

        {children}
      </body>
    </html>
  );
}
