import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Link href="/add_result" className="hover:text-[#62ff4d] px-10 py-2">
          Add Result
        </Link>
        <Link href="/add_update_student" className="hover:text-[#62ff4d] px-10 py-2">
          Add/Update
        </Link>
        <Link href="/generate_report" className="hover:text-[#62ff4d] px-10 py-2">
          Report
        </Link>
        <Link href="/mark_attendance" className="hover:text-[#62ff4d] px-10 py-2">
          Mark Attendance
        </Link>

        {children}
      </body>
    </html>
  );
}
